#TODO add an exception if token is not generated by function .fetch_token(); remove the exception from the main() function.

import passwords
import requests
import json
import os

from requests_oauthlib import OAuth2Session
from oauthlib.oauth2 import LegacyApplicationClient
#from chunk_vcf import FileInfo #TODO decide whether to define the class within cgg.py or keep it in chunk_vcf.py; package more of the chunk_vcf.py code into classes/functions. If I want to import only the class FileInfo from chunk_vcf.py, I need to package the rest of the logic in functions/main()/etc.

class FileInfo:
    """Create object with basic information to be used in VCF upload to Alissa via the API."""
    def __init__(self,originalPath,originalName):
        self.originalPath = originalPath
        self.originalName = originalName

class OAuth2Client:
    """Read credentials and return a token."""
    def __init__(self):
        self.username = passwords.alissa.username
        self.password = passwords.alissa.password
        self.client_id = passwords.alissa.username
        self.client_secret = passwords.alissa.password
        self.token_url = passwords.alissa.token_url
        self.session = OAuth2Session(client=LegacyApplicationClient(client_id=self.client_id))

        # TODO Add token timer
        self._token = None

    def fetch_token(self):
        """Fetch a token that is used for commands to Alissa such as creating a patient."""
        # TODO Add check for time since token made
        if self._token:
            return self._token

        response = self.session.fetch_token(token_url=self.token_url,
                                            username=self.username,
                                            password=self.password,
                                            client_id=self.client_id,
                                            client_secret=self.client_secret)
        # FIXME This could be done better
        if self.session.authorized:
            self._token = response['token_type'] + " " + response['access_token']

        return self._token

class cggPatient:
    """Create an object with information about a patient.

    In WOPR, the comments and family_id fields are not used. folder_name is usually Klinisk Genetik (KG) or Klinisk kemi (KK).
    """
    def __init__(self, token, accession_number,
                 folder_name='Default', sex='UNKNOWN', comments='', family_id=''):
        self.token = token
        self.accession_number = accession_number
        self.folder_name = folder_name
        self.sex = sex
        self.comments = comments
        self.family_id = family_id
        self.resource_url = passwords.alissa.bench_url + "/api/2/" + "patients"

    def get_existing_patient(self):
        """Return patient entry if it exists."""
        response = requests.get(self.resource_url,
                                params={'accessionNumber' : self.accession_number},
                                headers = {'Authorization' : self.token})
        patient_list = json.loads(response.text) # List of dict entries FIXME ??
        return patient_list[0] if patient_list is not None and len(patient_list) > 0 else None

    def exists(self):
        """Return patient entry exists."""
        return bool(self.get_existing_patient())

    def create(self):
        """Create the patient."""
        json_data = {
            'accessionNumber': self.accession_number,
            'folderName': self.folder_name,
            'gender': self.sex,
            'comments': self.comments,
            'familyIdentifier': self.family_id
        }
        response = requests.post(self.resource_url,
                                 data = json.dumps(json_data),
                                 headers = {'Authorization' : self.token,
                                            'Content-Type': 'application/json'})
        response_body = json.loads(response.text)
        if response_body is not None:
            return response_body['id']
        return        

#
#
# Patient query
#cf api_client.py from row 55, function get_patient_by_name in class PatientPublicApiConrollerClient
#and in bcm.py, from row 85. And then also at the bottom of bcm.py, from row 76 (not sure how that part works).
#
# VCF/file query
#cf bcm.py from row 42 - Check if data file already exists in the system. Function get_data_file_by_Name from api_client.py
#
# Patient post
#cf bcm.py from row 84; functions: get_patient_by_name, create_patient (caution! The create_patient from api_client.py, not from bcm.py) (why are there two functions with the same name? Not practical).
#

def get_data_file_by_Name(name, token) -> list:
    """Return a list with information about data file if it already exists in the system."""
    resource_url_postvcf = passwords.alissa.bench_url + "/api/2/" + "data_files"
    response = requests.get(resource_url_postvcf,
                            params={'name': name},
                            headers = {'Authorization' : token})
    return json.loads(response.text)  

def post_vcf_to_alissa(file_info : FileInfo, token):
    """Create post request for uploading a VCF from local machine to Alissa."""
    files_list=[ ('file',(file_info.originalName,open(file_info.originalPath,'rb'),'application/octet-stream'))]
    resource_url_postvcf = passwords.alissa.bench_url + "/api/2/" + "data_files"
    response = requests.post(resource_url_postvcf,
                             params = {'type': 'VCF_FILE'},
                             headers = {'Authorization' : token},
                             files = files_list)
    response_body = json.loads(response.text)
#    print(response_body)
    if response_body is not None:
        return response_body['id']
    return

def link_vcf_to_patient(patient_id, data_file_id, sample_identifier, token):
    """Create a lab result i.e. link a patient to a VCF file, using Alissa's internal identifiers.

    The sample identifier is the sample ID in the VCF file header line.
    """
    lab_result_url = passwords.alissa.bench_url + "/api/2/" + "patients/" + str(patient_id) + "/lab_results"
    json_data = {
        'dataFileId' : data_file_id,
        'sampleIdentifier' : sample_identifier
    }
    response = requests.post(lab_result_url,
                            data = json.dumps(json_data),
                            headers = {'Authorization' : token, 'Content-Type': 'application/json'})
    response_body = json.loads(response.text)
#    print(response_body)
    if response_body is not None:
        return response_body['id']
    return

 
def main():
    oauth2_client = OAuth2Client()
    token = oauth2_client.fetch_token()

    if token:
	
	#Parameters required for 1-creating patient, 2-uploading VCF file and 3-linking patient and VCF file.
        accession_number = "test-patient_220221_3" #SLIMS: Sctx.sample_name
        folder_name = "Default" #SLIMS: department_translate[Sctx.slims_info['department']], default: "Default"
        patient_sex = "FEMALE" #SLIMS: Sctx.slims_info['gender'], default: "UNKNOWN"
        path = '/home/xbregw/Alissa_upload/VCFs/known_variants_220221_2.vcf.gz' #SLIMS: Sctx.snv_cnv_vcf_path
        name_in_vcf = "NA12878" #That is the sample ID in the VCF header row. In WOPR, it should be the same as Sctx.sample_name

        #Check whether a patient exists, if not: create it. In both cases: return internal patient id.
        patient = cggPatient(token, accession_number, folder_name, patient_sex)
        if patient.exists():     #An alternative to this function is to check whether the response of get_existing_patient is "None" (cf Agilent bcm.py row 88).
            print('Patient exists.')
            existing_patient = patient.get_existing_patient()
            patient_id = existing_patient['id']
        else:
            patient_id = patient.create()
        print(patient_id)
        
        #Check whether a data file exists, if not: upload it. In both cases: return internal data file id.
        name = os.path.basename(path)
        data_file = get_data_file_by_Name(name, token)
        if len(data_file) > 0:
            print('A VCF file with the same name already exists. Not attempting to upload it again.')
            data_file_id = data_file[0]['id']
        else: 
            vcf_file_info = FileInfo(path,name)
            data_file_id = post_vcf_to_alissa(vcf_file_info, token)
        print(data_file_id)

        #Link data file to patient (i.e. create a lab result). If the lab result already exists: this will result in an error.
        labresult = link_vcf_to_patient(patient_id, data_file_id, name_in_vcf, token)
        print(labresult)

    else:
        # TODO Add a raise for custom Exception or built-in
        raise Exception('No token was generated. Investigate!')
   
if __name__ == '__main__':

    main()
